package ru.krezd.diploma.dto.slurm.node;

public enum SlurmNodeState {
    INVALID,
    UNKNOWN,
    DOWN,
    IDLE,
    ALLOCATED,
    ERROR,
    MIXED,
    FUTURE,
    PERFCTRS,
    RESERVED,
    UNDRAIN,
    CLOUD,
    RESUME,
    DRAIN,
    COMPLETING,
    NOT_RESPONDING,
    POWERED_DOWN,
    FAIL,
    POWERING_UP,
    MAINTENANCE,
    REBOOT_REQUESTED,
    REBOOT_CANCELED,
    POWERING_DOWN,
    DYNAMIC_FUTURE,
    REBOOT_ISSUED,
    PLANNED,
    INVALID_REG,
    POWER_DOWN,
    POWER_UP,
    POWER_DRAIN,
    DYNAMIC_NORM
}
