version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: diploma-postgres
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5432:5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - diploma_app
    restart: unless-stopped

  mysql_slurm:
    image: mysql:8
    container_name: mysql_slurm
    environment:
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurm_secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - mysql_slurm_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"   # Только localhost — slurmdbd на том же хосте
    networks:
      - slurm_network
    restart: unless-stopped
    command:
      - "character-set-server=utf8mb4"
      - "collation-server=utf8mb4_unicode_ci"
      - "innodb-buffer-pool-size=256M"
      - "innodb-lock-wait-timeout=900"

  frontend:
    build: ../frontend
    container_name: diploma-frontend
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - diploma_app

volumes:
  pgdata:
  mysql_slurm_data:

networks:
  diploma_app:
  slurm_network: