export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    REGISTRATION_STATUS: '/auth/registration-status',
  },
  USERS: {
    ME: '/users/me',
    ME_PASSWORD: '/users/me/password',
    LIST: '/users',
    CREATE: '/users',
    UPDATE: (username: string) => `/users/${username}`,
    DELETE: (username: string) => `/users/${username}`,
    SETTINGS_REGISTRATION: '/users/settings/registration',
  },
  SLURM: {
    // Активные задания (slurmctld)
    JOBS: '/slurm/jobs',
    USER_JOBS: '/slurm/user/jobs',
    JOB: (id: number) => `/slurm/job/${id}`,
    JOB_SUBMIT: '/slurm/job/submit',
    JOB_CANCEL: (id: number) => `/slurm/job/${id}`,
    JOB_UPDATE: (id: number) => `/slurm/job/${id}`,
    // Архивные задания (slurmdbd)
    JOBS_HISTORY: '/slurm/jobs/history',
    USER_JOBS_HISTORY: '/slurm/user/jobs/history',
    JOB_HISTORY: (id: number) => `/slurm/job/${id}/history`,
    // Usage статистика
    JOBS_USAGE: '/slurm/jobs/usage',
    USER_JOBS_USAGE: '/slurm/user/jobs/usage',
    USER_ASSOCIATIONS: '/slurm/user/associations',
    USER_ACCOUNT_ASSOCIATIONS: '/slurm/user/account-associations',
    USER_QOS: '/slurm/user/qos',
    // Узлы
    NODES: '/slurm/nodes',
    NODE: (name: string) => `/slurm/node/${name}`,
    PARTITIONS: '/slurm/partitions',
    PARTITION: (name: string) => `/slurm/partition/${name}`,
    DIAG: '/slurm/diag',
    PING: '/slurm/ping',
    // Аккаунты и ассоциации
    ACCOUNTS: '/slurm/accounts',
    ACCOUNT: (name: string) => `/slurm/accounts/${name}`,
    ASSOCIATIONS: '/slurm/associations',
    DB_CONFIG: '/slurm/db/config',
    QOS_LIST: '/slurm/qos',
    QOS: (name: string) => `/slurm/qos/${name}`,
    TRES: '/slurm/tres',
    ASSOCIATIONS_QOS: '/slurm/associations/qos',
    ASSOCIATIONS_LIMITS: '/slurm/associations/limits',
  },
  SOFTWARE: {
    LIST: '/software',
    SCAN: '/software/scan',
    REGISTER: '/software/register',
    UPLOAD: '/software/upload',
    UPDATE: (id: number) => `/software/${id}`,
    MODULEFILE: (id: number) => `/software/${id}/modulefile`,
    STATUS: (id: number) => `/software/${id}/status`,
    DELETE: (id: number) => `/software/${id}`,
  },
  JOB_TEMPLATES: {
    LIST: '/jobs/templates',
    CREATE: '/jobs/templates',
    UPDATE: (id: number) => `/jobs/templates/${id}`,
    DELETE: (id: number) => `/jobs/templates/${id}`,
  },
  FILES: {
    // Эндпоинты для любого авторизованного пользователя (путь в рамках своей папки)
    USER: {
      LIST: '/files/user/list',
      UPLOAD: '/files/user/upload',
      CREATE_DIR: '/files/user/createDir',
      DOWNLOAD: '/files/user/download',
      DOWNLOAD_ZIP: '/files/user/download-zip',
      DELETE: '/files/user/delete',
    },
    // Эндпоинты только для ADMIN (полный доступ ко всем директориям)
    ADMIN: {
      LIST: '/files/admin/list',
      UPLOAD: '/files/admin/upload',
      CREATE_DIR: '/files/admin/createDir',
      DOWNLOAD: '/files/admin/download',
      DOWNLOAD_ZIP: '/files/admin/download-zip',
      DELETE: '/files/admin/delete',
    },
  },
} as const;