spring.application.name=diploma

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/diploma
spring.datasource.username=postgres
spring.datasource.password=admin

jwt.secret=secret
jwt.accessTtl=6000
jwt.refreshTtl=12000

root.path=D:\
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

server.address=0.0.0.0
server.port=8080
