spring.datasource.url=jdbc:postgresql://postgres:5432/diploma
spring.datasource.username=postgres
spring.datasource.password=admin

jwt.secret=secret
jwt.accessTtl=6000
jwt.refreshTtl=12000

root.path=/data