spring.application.name=diploma

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://192.168.0.18:5432/diploma
spring.datasource.username=postgres
spring.datasource.password=admin

jwt.secret=secret
jwt.accessTtl=6000
jwt.refreshTtl=12000

root.path=/shared/workspace/diploma-app/
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

server.address=0.0.0.0
server.port=8080

logging.level.ru.krezd.diploma.interceptor.SlurmRequestLoggingInterceptor=DEBUG
logging.level.ru.krezd.diploma.service.SlurmAccountService=DEBUG

slurm.group.user=slurm-user
slurm.group.admin=slurm
slurm.token.lifetime=1800
slurm.rest.address=http://localhost:6820/slurm/v0.0.40/
slurm.db.address=http://localhost:6820/slurmdb/v0.0.40/
slurm.jwt.key-path=/var/spool/slurm/ctld/jwt_hs256.key
slurm.cluster.name=diplomacluster
slurm.default.account=user
slurm.admin.account=admin

software.path=/shared/software/
software.modules.path=/shared/software/modules/